### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by blootsvoets** [aphp/Cohort360-Back-end#11]
This looks like a promising project. Would you please add an open source license (e.g., Apache License 2.0 like in the frontend project) so that we can test this in our environment?

**Comment by Dubrzr** [comment]
Hi @blootsvoets, we'll do that next week with Apache Licence 2.0, thanks for the remark!
cc @alexandreMartinEcl 

For more information, please contact us at **firstname**.**lastname**@aphp.fr (check out my profile to replace correctly).

**Comment by alexandreMartinEcl** [comment]
Hello @blootsvoets, thank you for the interest you have on our project. I just added the license on the dev branch

Once again if you have any questions, or any suggestions, notably for making the project more adaptative, feel free to send us a message
